# Generated by Django 3.0.3 on 2020-12-27 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account_status',
            fields=[
                ('idStatus', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('idAccount', models.AutoField(primary_key=True, serialize=False)),
                ('activated_date', models.DateField()),
                ('last_access', models.DateTimeField(auto_now_add=True)),
                ('balance', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='cardType',
            fields=[
                ('idType', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='gender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender_type', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='transcations',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=60)),
                ('tran_time', models.DateTimeField(auto_now_add=True)),
                ('balance', models.FloatField()),
                ('account_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Atm_app.Accounts')),
            ],
        ),
        migrations.CreateModel(
            name='customer',
            fields=[
                ('customerID', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=30)),
                ('address', models.TextField()),
                ('dob', models.DateField()),
                ('email', models.CharField(max_length=50)),
                ('Phone_num', models.CharField(max_length=10)),
                ('img', models.ImageField(upload_to='profile')),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Atm_app.gender')),
            ],
        ),
        migrations.CreateModel(
            name='cardDetails',
            fields=[
                ('numCard', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('expire_year', models.IntegerField()),
                ('expire_month', models.IntegerField()),
                ('max_amount', models.FloatField()),
                ('pin', models.CharField(max_length=4)),
                ('idAccount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Atm_app.Accounts')),
                ('numType', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Atm_app.cardType')),
            ],
        ),
        migrations.AddField(
            model_name='accounts',
            name='hold_on',
            field=models.ManyToManyField(to='Atm_app.customer'),
        ),
        migrations.AddField(
            model_name='accounts',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Atm_app.Account_status'),
        ),
    ]
