# Generated by Django 3.0.3 on 2021-01-06 12:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Atm_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='last_access',
            field=models.DateTimeField(default=django.utils.timezone.localtime),
        ),
        migrations.AlterField(
            model_name='carddetails',
            name='last_pinChange',
            field=models.DateTimeField(default=django.utils.timezone.localtime),
        ),
        migrations.AlterField(
            model_name='transcations',
            name='tran_time',
            field=models.DateTimeField(default=django.utils.timezone.localtime),
        ),
    ]
