# Generated by Django 3.0.3 on 2021-01-03 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Atm_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='loan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ammount', models.FloatField()),
                ('accound_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Atm_app.Accounts')),
            ],
        ),
    ]
