# Generated by Django 3.0.3 on 2021-01-04 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Atm_app', '0002_loan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan',
            name='id',
        ),
        migrations.AlterField(
            model_name='loan',
            name='accound_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Atm_app.Accounts'),
        ),
    ]
