# Generated by Django 3.0.3 on 2021-01-06 12:15

import Atm_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Atm_app', '0002_auto_20210106_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='last_access',
            field=models.DateTimeField(default=Atm_app.models.now),
        ),
        migrations.AlterField(
            model_name='carddetails',
            name='last_pinChange',
            field=models.DateTimeField(default=Atm_app.models.now),
        ),
        migrations.AlterField(
            model_name='transcations',
            name='tran_time',
            field=models.DateTimeField(default=Atm_app.models.now),
        ),
    ]
