# Generated by Django 3.0.3 on 2021-01-09 11:20

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Atm_app', '0003_auto_20210106_1745'),
    ]

    operations = [
        migrations.CreateModel(
            name='login_trace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.TimeField(auto_now_add=datetime.time(16, 50, 50, 445447))),
                ('card_num', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Atm_app.cardDetails')),
            ],
        ),
    ]
