# Generated by Django 3.0.3 on 2021-01-09 11:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Atm_app', '0004_login_trace'),
    ]

    operations = [
        migrations.AddField(
            model_name='login_trace',
            name='time',
            field=models.TimeField(default=datetime.time(17, 2, 38, 811330)),
        ),
        migrations.AlterField(
            model_name='login_trace',
            name='date',
            field=models.DateField(default=datetime.date(2021, 1, 9)),
        ),
    ]
