# Generated by Django 3.0.3 on 2021-01-10 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Atm_app', '0005_auto_20210109_1702'),
    ]

    operations = [
        migrations.DeleteModel(
            name='login_trace',
        ),
    ]
